// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SPack$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SPack";
  readonly sourceName: "contracts/SPack.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220eb0b86d794c70b76e18d2b0580d8ea3603cd1673bd463ed83325c28ce994532864736f6c63430008140033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220eb0b86d794c70b76e18d2b0580d8ea3603cd1673bd463ed83325c28ce994532864736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/SPack.sol";
  readonly buildInfoId: "solc-0_8_20-309dc64c26e9b0680caf0e767bac9c02027a25a0";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SPack"]: SPack$Type;
    ["contracts/SPack.sol:SPack"]: SPack$Type;
  }
}